server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/MovieRealm

database:
  host: remote:localhost
  dbname: MovieDB
  username: root
  password: root
