server:
  port: 9000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
spring:
   main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
   cloud:
    gateway:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*" 
   cloud:
     gateway:
       routes:
        - id: movieService
          uri: lb://MOVIE-SERVICE
          predicates:
           - Path=/movieapp/**
